# Generated by Django 5.2.7 on 2025-11-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='Unnamed Class', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Unnamed Subject', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Unnamed Teacher', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
    ]
